Qa/pagination
singer-io/tap-hubspot pull request #166
Opened 2021-09-14 17:50 UTC by yusaku2

# Description of change
https://jira.talendforge.org/browse/TDL-14768
Testing pagination in tap-Hubspot
# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-09-14 20:51 UTC, kspeer825 requested changes
Test looks great, most of my comments are just cleanup stuff.

2021-09-14 20:51 UTC, kspeer825 commented on tests/client.py
> +
we could add an else raise NotImplementedError here.

2021-09-14 20:51 UTC, kspeer825 commented on tests/client.py
> +            #response = self.get(child_url, params=params)
This can just be deleted

2021-09-14 20:51 UTC, kspeer825 commented on tests/client.py
> +            #records.extend(response['timeline'])
This can be dropped.

2021-09-14 20:51 UTC, kspeer825 commented on tests/client.py
> +        # a_sub_id =random.choice([item[0] for item in subscription_id_list if item[0]])
This can be dropped.

2021-09-14 20:51 UTC, kspeer825 commented on tests/test_hubspot_pagination_test.py
> +                # existing_records['subscription_changes'] = test_client.get_subscription_changes()  # see BUG_TDL-14938
I think you can drop this, the bug is marked in other tests and it looks like you were still able to test it.

2021-09-14 20:51 UTC, kspeer825 commented on tests/test_hubspot_pagination_test.py
> +                    test_client.create(stream, subscriptions=existing_records[stream], times=under_target)
I don't think we want to make this call if under_target is zero. I think `if under_target >= 0` should change to `under_target > 0`

2021-09-14 20:51 UTC, kspeer825 commented on tests/test_hubspot_pagination_test.py
> +        streams_to_test =  set(stream for stream, limit in self.expected_page_limits().items() if limit != set())
this doesn't really matter, but it would also work if you only did ` if limit` since `bool(set())` is False.

2021-09-14 20:51 UTC, kspeer825 commented on tests/test_hubspot_pagination_test.py
> +        #self.select_all_streams_and_fields(conn_id, catalog_entries, select_all_fields=True)
This can be deleted.

2021-09-17 15:11 UTC, kspeer825 approved these changes
Looks great!

2021-09-17 15:11 UTC, kspeer825 commented on tests/test_hubspot_all_fields_test.py
> +        #    'subscription_changes', # BUG_TDL-14938 https://jira.talendforge.org/browse/TDL-14938
Just some cleanup here

2021-09-17 15:39 UTC, yusaku2 commented on tests/test_hubspot_all_fields_test.py
> +        #    'subscription_changes', # BUG_TDL-14938 https://jira.talendforge.org/browse/TDL-14938
will fix in next pr

2021-09-17 18:27 UTC, merged