Clear bookmark for existing connection.
singer-io/tap-hubspot pull request #196
Opened 2022-06-09 09:48 UTC by prijendev

# Description of change
- Clear bookmark for existing connections that are using `hs_lastmodifieddate` as replication key.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-06-10 09:33 UTC, dbshah1212 approved these changes

2022-06-10 11:14 UTC, karanpanchal-crest requested changes

2022-06-10 11:14 UTC, karanpanchal-crest commented on tap_hubspot/__init__.py
>      bookmark_field_in_record = 'hs_lastmodifieddate'
Change the variable name to "last_modified_date" for readability

2022-06-10 12:31 UTC, prijendev commented on tap_hubspot/__init__.py
> +        if older_bookmark_key:
Added comment.

2022-06-10 14:14 UTC, karanpanchal-crest requested changes

2022-06-10 14:14 UTC, karanpanchal-crest commented on tap_hubspot/tests/unittests/test_get_start.py
> +        mock_state = {
@prijendev, please make the function "get_state" to attach as many keys in the dictionary

2022-06-10 14:24 UTC, karanpanchal-crest approved these changes

2022-07-15 13:19 UTC, kspeer825 reviewed
Will the old bookmark key be removed from state after syncing and saving the new bookmark key to state?

2022-07-18 10:23 UTC, prijendev commented
> Will the old bookmark key be removed from state after syncing and saving the new bookmark key to state?

No, the existing bookmark key will not be removed from the state after sync. Instead, the tap will save the old bookmark key and the new bookmark key in the state.

2022-07-20 17:56 UTC, kspeer825 commented
> [ View changes ](/singer-io/tap-hubspot/pull/196/files/e416cbf63cc8396f2c4b0f35b5f93bacd4300458)

I don't know if we should be saving an old key and value in state that will never be used. Can this just be replaced instead? Might be good to get some internal dev input here.

2022-07-21 12:22 UTC, prijendev commented
> > [ View changes ](/singer-io/tap-hubspot/pull/196/files/e416cbf63cc8396f2c4b0f35b5f93bacd4300458)
> 
> I don't know if we should be saving an old key and value in state that will never be used. Can this just be replaced instead? Might be good to get some internal dev input here.

@kspeer825  I think we should keep the old bookmark key in the state for backward compatibility. We have discussed the same thing with @cosimon and concluded to keep the old bookmark key in the state in case we need to revert back for any client.

2022-07-21 13:25 UTC, kspeer825 approved these changes

2022-07-25 11:46 UTC, RushiT0122 approved these changes

2022-07-29 05:46 UTC, merged